# Generated by Django 2.0.5 on 2018-05-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
