# Generated by Django 2.0.5 on 2018-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Description',
            field=models.TextField(default='description default text'),
        ),
    ]
